# Generated by Django 5.1.7 on 2025-03-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('site_name', models.CharField(default='E-Shop', max_length=255)),
                ('site_url', models.URLField(default='http://127.0.0.1:8000')),
                ('enable_2fa', models.BooleanField(default=True)),
                ('allow_admin_registration', models.BooleanField(default=False)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
