# Generated by Django 5.1.6 on 2025-03-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderitem_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
